### ISSUE TITLE
Script fails for optimization calculations

### ISSUE THREAD

**Issue by Llystrom** [dmsteglenko/Fukui-function-calculation#1]
Hello,

First I would like to thank you for your script, it will save me much time coding the method from "A direct evaluation of regional Fukui functions in molecules."

However, when I tested your script on an optimization calculation I found that it only looks at the data related to the initial geometry not the optimized geometry. I was wondering if you would think about adding a check to see if the calculation were optimization, that way it would skip the data for the initial geometry? I would modify the code but it is only binary, so I will remove the data for the initial geometry if the code is not modified.

Thank you again,

Levi

**Comment by dmsteglenko** [comment]
Hello Levi,


This console program is designed to work with single point calculation files.
How to use this program:
1. Optimize the geometry of your molecule.
2. Take the equilibrium geometry that you obtained in the first step and perform a single point calculation with the parameters iop (3/33 = 1) pop = full (pop = full can be changed to iop (6/7 = 3)).
3. Now you can run the program:     ./fukui  your_molekule .out
or:      ./fukui  your_molecule .log
where the file your_molecule .out is the file obtained in the second step.

Thus, the program works with a single point calculation file.

**Comment by Llystrom** [comment]
Thank You, 

I have used the console program as you described. 

I only asked about using the script on an optimization calculations to reduce the human interaction and reducing the number of calculations during a high throughput screening.

I will use your program as written.

Thanks again for your quick reply! :)
  
Levi
